apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: fluent-bit
data:
{{- range $path, $config := .Values.fluentbitConfig }}
  {{ $path }}: |
{{ tpl $config $ | indent 4 -}}
{{- end -}}