apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: {{ .Values.namespace }}
data:
  logstash.conf: |-
    input {
      http {
        port => 8080
      }
    }
    filter {
      prune {
        blacklist_values => {
          "log" => "(MYSQL_PASSWORD|AWS_SECRET)"
        }
      }
    }
    output {
      loggly {
        key => ""
        tag => "logstash,kubernetes"
        host => "logs-01.loggly.com"
        proto => "https"
      }
    }
