apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.logstash.appname }}
  labels:
    app: {{ .Values.logstash.appname }}
spec:
  replicas: {{ .Values.logstash.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.logstash.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.logstash.appname }}
    spec:
      containers:
        - name: {{ .Values.logstash.appname }}
          image: "{{ .Values.logstash.image.name }}:{{ .Values.logstash.image.tag }}"
          command:
            - '/bin/sh'
            - '-c'
            - 'logstash-plugin install logstash-output-loggly && logstash-plugin install logstash-filter-prune && /usr/local/bin/docker-entrypoint '
          ports:
            - containerPort: {{ .Values.logstash.port }}
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "200m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.logstash.port }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.logstash.port }}
            initialDelaySeconds: {{ .Values.logstash.deployment.initialDelaySeconds }}
            periodSeconds: {{ .Values.logstash.deployment.periodSeconds }}
            timeoutSeconds: {{ .Values.logstash.deployment.timeoutSeconds }}
          volumeMounts:
            - name: config
              mountPath: /usr/share/logstash/pipeline
          env:
            - name: XPACK_MONITORING_ENABLED
              value: "false"
      volumes:
        - name: config
          configMap:
            name: logstash-config
            items:
              - key: logstash.conf
                path: logstash.conf
