kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: logstash-svc
spec:
  selector:
    app: {{ .Values.logstash.appname }}
  ports:
    - name: http
      port: {{ .Values.logstash.port }}
      targetPort: {{ .Values.logstash.port }}

