kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: logstash-svc
spec:
  selector:
    app: logstash
  ports:
    - name: http
      port: 8080
      targetPort: 8080

